# Generated by Django 4.0 on 2022-10-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0002_alter_benefits_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='is_golden',
            field=models.BooleanField(default=False),
        ),
    ]
