# Generated by Django 4.0 on 2022-10-11 11:18

from django.db import migrations, models
import django.db.models.deletion
import khayyam.jalali_datetime


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MovieCrawl', '0007_alter_actormovie_movie_id_movieimages'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=khayyam.jalali_datetime.JalaliDatetime.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='useraccount', to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='BasketLines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket', to='Account.account')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase', to='MovieCrawl.movie')),
            ],
        ),
    ]
