# Generated by Django 4.0 on 2022-10-24 17:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='invoice_number',
            field=models.UUIDField(default=uuid.UUID('8128e2ba-9e50-4624-8daf-0b84bb7ab007'), verbose_name='invoice number'),
        ),
    ]
