# Generated by Django 4.0 on 2022-10-25 08:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0002_alter_payment_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='gateway',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='financial.gateway', verbose_name='gateways'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='invoice_number',
            field=models.UUIDField(default=uuid.UUID('afc5ea24-9405-4155-9f1d-55e20a942f45'), unique=True, verbose_name='invoice number'),
        ),
    ]
