# Generated by Django 4.0 on 2022-09-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieCrawl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='modify_date',
            field=models.DateTimeField(default='1401-07-08 15:01:00.811672'),
        ),
        migrations.AddField(
            model_name='movie',
            name='register_date',
            field=models.DateTimeField(default='1401-07-08 15:01:00.811436'),
        ),
    ]
