# Generated by Django 4.0 on 2022-09-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieCrawl', '0002_movie_modify_date_movie_register_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='modify_date',
            field=models.DateTimeField(default='1401-07-08 15:02:26.791870'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='register_date',
            field=models.DateTimeField(default='1401-07-08 15:02:26.791649'),
        ),
    ]
