# Generated by Django 4.0 on 2022-10-01 12:06

from django.db import migrations, models
import khayyam.jalali_datetime


class Migration(migrations.Migration):

    dependencies = [
        ('MovieCrawl', '0003_movie_comment_alter_movie_modify_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rate',
            field=models.PositiveIntegerField(choices=[(1, 'Integer'), (2, 'String'), (3, 'Float')], default=1),
        ),
        migrations.AlterField(
            model_name='movie',
            name='modify_date',
            field=models.DateTimeField(default=khayyam.jalali_datetime.JalaliDatetime.now),
        ),
        migrations.AlterField(
            model_name='movie',
            name='register_date',
            field=models.DateTimeField(default=khayyam.jalali_datetime.JalaliDatetime.now),
        ),
    ]
