# Generated by Django 4.0 on 2022-10-01 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MovieCrawl', '0005_movie_is_active_alter_movie_rate_alter_movie_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenreMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moviegenres', to='MovieCrawl.genre')),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='genresmovies', to='MovieCrawl.movie')),
            ],
        ),
    ]
