# Generated by Django 4.0 on 2022-10-02 17:27

from django.db import migrations, models
import django.db.models.deletion
import khayyam.jalali_datetime


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(null=True)),
                ('moment', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_balance', to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveIntegerField(choices=[(1, 'charge'), (2, 'transfer'), (3, 'Credit')], default=3)),
                ('amount', models.IntegerField(null=True)),
                ('updateDate', models.DateTimeField(default=khayyam.jalali_datetime.JalaliDatetime.today)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_trans', to='auth.user')),
            ],
        ),
    ]
