# Generated by Django 4.0 on 2022-10-06 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'charge'), (4, 'variz'), (3, 'daryaft'), (2, 'cash')], default=2),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='user_trans', to='auth.user'),
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_node', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='receiver', to='auth.user')),
                ('sender_node', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sender', to='auth.user')),
            ],
        ),
    ]
