# Generated by Django 4.0 on 2022-10-06 10:57

from django.db import migrations, models
import django.db.models.deletion
import khayyam.jalali_datetime


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transaction_amount_alter_transaction_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='updateDate',
            field=models.DateTimeField(default=khayyam.jalali_datetime.JalaliDatetime.now),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='receiver_node',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='receiver', to='transactions.transaction'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='sender_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sender', to='transactions.transaction'),
        ),
    ]
