# Generated by Django 4.0 on 2022-10-16 09:24

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='address',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=14, region='IR', unique=True),
        ),
    ]
