# Generated by Django 4.0 on 2022-10-19 08:19

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0002_alter_shipping_address_alter_shipping_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=14, null=True, region='IR'),
        ),
    ]
